### ISSUE TITLE
Network error on real devices : Android

### ISSUE THREAD

**Issue by chit786** [javebratt/ionic-firebase-email-auth#4]
HI ,

After following your tutorials and having tried various things i am writing here one issue which I am facing on real devices

My github repo:

https://github.com/chit786/WeSnap

admin-login.ts file has the login component code 

android-sdk/24.4.1_1

tried on 4.4 android and Nexus 6, 5.1 but same behavior

<img width="379" alt="screen shot 2017-03-19 at 12 28 01" src="https://cloud.githubusercontent.com/assets/18376182/24080442/8ed688b4-0c9f-11e7-99c2-65f31f40eb67.png">

I investigated following things : 

1. Checked in debugger so there is no network call happening after clicking submit button when error comes as shown in screenshot!
2. Somehow the app is blocking
3. white-list plugin is added
4. config.xml is almost same as yours

After searching a lot on internet and investigating so much time into this I seek help if you can!

Thank you very much in advance!

**Comment by javebratt** [comment]
Hey @chit786 why are you creating timeouts in the code? `this.authData.createTimeout(5000).then()`?

I don't see anything wrong with the code, tho I need to clean it up more and remove unnecessary stuff, have you tried cloning the repo and running it fresh to see if you get the error?

**Comment by chit786** [comment]
Hi Jorge,

Thanks for reply,

Yes the timeout I kept was intensional since I was trying to check the network call but even if removing the same do not help much. Issue is still there.

i tried to make a clone as well but I believe the issue lies somewhere with the Android SDK where its not allowing the network call for some time.

Or 

Second thing i can think of is when we do a session sign out some promise is still hanging, but I am not able to identify which one.

thanks again! would really appreciate your help on this.

**Comment by javebratt** [comment]
@chit786 I just cloned your repository, ran `npm install` and then did an `ionic run android` it worked without modifying any code.

I'm running on a Samsung Galaxy S4 with Android 4.4, could it be the environment where you're trying to run it? Have you deleted the `node_modules/` folder and tried a clean install?

Since the problem doesn't seem to be in the code I'm going to close the issue (_also I'm going to update the repo_) but if you're stuck, feel free to email me => j@javebratt.com I'll do my best to help you debug it.
